runtime: python39
instance_class: F2
automatic_scaling:
  max_instances: 25
  min_instances: 0
  min_idle_instances: 0
  max_idle_instances: 2

entrypoint: gunicorn -b :$PORT app:app

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

- url: /_ah/warmup
  script: auto

inbound_services:
- warmup
